// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipe.Entities.DbContexts;

#nullable disable

namespace Recipe.Entities.Migrations
{
    [DbContext(typeof(sqlContext))]
    [Migration("20240721204246_entitiesChangedNull")]
    partial class entitiesChangedNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 21, 20, 42, 45, 314, DateTimeKind.Utc).AddTicks(8814));

                    b.HasKey("ID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.HasIndex("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Bakliyat Yemekleri",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Çorba Tarifleri",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Dolma-Sarma Tarifleri",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Et Yemekleri",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Hamur İşi Tarifleri",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Kahvaltılık Tarifleri",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Makarna Tarifleri",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Sebze Yemekleri",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Tatlı Tarifleri",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.CategoryFood", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("CategoryFoods");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            FoodId = 11
                        },
                        new
                        {
                            CategoryId = 1,
                            FoodId = 13
                        },
                        new
                        {
                            CategoryId = 1,
                            FoodId = 14
                        },
                        new
                        {
                            CategoryId = 1,
                            FoodId = 15
                        },
                        new
                        {
                            CategoryId = 1,
                            FoodId = 16
                        },
                        new
                        {
                            CategoryId = 1,
                            FoodId = 17
                        },
                        new
                        {
                            CategoryId = 1,
                            FoodId = 18
                        },
                        new
                        {
                            CategoryId = 1,
                            FoodId = 19
                        },
                        new
                        {
                            CategoryId = 6,
                            FoodId = 19
                        },
                        new
                        {
                            CategoryId = 8,
                            FoodId = 19
                        },
                        new
                        {
                            CategoryId = 1,
                            FoodId = 20
                        },
                        new
                        {
                            CategoryId = 9,
                            FoodId = 12
                        },
                        new
                        {
                            CategoryId = 9,
                            FoodId = 44
                        },
                        new
                        {
                            CategoryId = 9,
                            FoodId = 52
                        },
                        new
                        {
                            CategoryId = 2,
                            FoodId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            FoodId = 2
                        },
                        new
                        {
                            CategoryId = 2,
                            FoodId = 3
                        },
                        new
                        {
                            CategoryId = 2,
                            FoodId = 4
                        },
                        new
                        {
                            CategoryId = 2,
                            FoodId = 5
                        },
                        new
                        {
                            CategoryId = 2,
                            FoodId = 6
                        },
                        new
                        {
                            CategoryId = 2,
                            FoodId = 7
                        },
                        new
                        {
                            CategoryId = 2,
                            FoodId = 8
                        },
                        new
                        {
                            CategoryId = 2,
                            FoodId = 9
                        },
                        new
                        {
                            CategoryId = 2,
                            FoodId = 10
                        },
                        new
                        {
                            CategoryId = 3,
                            FoodId = 21
                        },
                        new
                        {
                            CategoryId = 3,
                            FoodId = 22
                        },
                        new
                        {
                            CategoryId = 3,
                            FoodId = 23
                        },
                        new
                        {
                            CategoryId = 3,
                            FoodId = 24
                        },
                        new
                        {
                            CategoryId = 3,
                            FoodId = 25
                        },
                        new
                        {
                            CategoryId = 3,
                            FoodId = 26
                        },
                        new
                        {
                            CategoryId = 3,
                            FoodId = 27
                        },
                        new
                        {
                            CategoryId = 3,
                            FoodId = 28
                        },
                        new
                        {
                            CategoryId = 3,
                            FoodId = 29
                        },
                        new
                        {
                            CategoryId = 3,
                            FoodId = 30
                        },
                        new
                        {
                            CategoryId = 4,
                            FoodId = 31
                        },
                        new
                        {
                            CategoryId = 4,
                            FoodId = 32
                        },
                        new
                        {
                            CategoryId = 4,
                            FoodId = 33
                        },
                        new
                        {
                            CategoryId = 4,
                            FoodId = 34
                        },
                        new
                        {
                            CategoryId = 4,
                            FoodId = 35
                        },
                        new
                        {
                            CategoryId = 5,
                            FoodId = 36
                        },
                        new
                        {
                            CategoryId = 5,
                            FoodId = 37
                        },
                        new
                        {
                            CategoryId = 5,
                            FoodId = 38
                        },
                        new
                        {
                            CategoryId = 5,
                            FoodId = 39
                        },
                        new
                        {
                            CategoryId = 5,
                            FoodId = 40
                        },
                        new
                        {
                            CategoryId = 6,
                            FoodId = 41
                        },
                        new
                        {
                            CategoryId = 6,
                            FoodId = 42
                        },
                        new
                        {
                            CategoryId = 6,
                            FoodId = 43
                        },
                        new
                        {
                            CategoryId = 6,
                            FoodId = 45
                        },
                        new
                        {
                            CategoryId = 7,
                            FoodId = 46
                        },
                        new
                        {
                            CategoryId = 7,
                            FoodId = 47
                        },
                        new
                        {
                            CategoryId = 7,
                            FoodId = 48
                        },
                        new
                        {
                            CategoryId = 7,
                            FoodId = 49
                        },
                        new
                        {
                            CategoryId = 7,
                            FoodId = 50
                        },
                        new
                        {
                            CategoryId = 8,
                            FoodId = 51
                        },
                        new
                        {
                            CategoryId = 8,
                            FoodId = 53
                        },
                        new
                        {
                            CategoryId = 8,
                            FoodId = 54
                        },
                        new
                        {
                            CategoryId = 8,
                            FoodId = 55
                        },
                        new
                        {
                            CategoryId = 9,
                            FoodId = 56
                        },
                        new
                        {
                            CategoryId = 9,
                            FoodId = 57
                        },
                        new
                        {
                            CategoryId = 9,
                            FoodId = 58
                        },
                        new
                        {
                            CategoryId = 9,
                            FoodId = 59
                        },
                        new
                        {
                            CategoryId = 9,
                            FoodId = 60
                        });
                });

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.Comments", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CommentTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 21, 20, 42, 45, 316, DateTimeKind.Utc).AddTicks(245));

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ID");

                    b.HasIndex("FoodId");

                    b.HasIndex("ID");

                    b.ToTable("Comments", t =>
                        {
                            t.HasCheckConstraint("Stars", "[Stars]>=0 AND [Stars]<=5");
                        });
                });

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.Food", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CookingTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 21, 20, 42, 45, 316, DateTimeKind.Utc).AddTicks(5404));

                    b.Property<string>("HowManyPerson")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Like")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PictureOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreparationTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecipeExplanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            ID = 3,
                            CookingTime = "30 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Kırmızı mercimek, soğan, havuç, patates, su, tuz, karabiber, tereyağı",
                            Name = "Mercimek Çorbası",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Mercimekleri, soğanı, havucu ve patatesi haşlayın, blenderdan geçirin ve tereyağında kavurun."
                        },
                        new
                        {
                            ID = 2,
                            CookingTime = "35 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Kırmızı mercimek, bulgur, pirinç, soğan, domates salçası, biber salçası, su, tuz, nane, tereyağı",
                            Name = "Ezogelin Çorbası",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Mercimek, bulgur ve pirinci haşlayın. Soğanı kavurun, salçaları ekleyin ve haşlanmış malzemelerle karıştırın."
                        },
                        new
                        {
                            ID = 1,
                            CookingTime = "20 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Yoğurt, un, yumurta, su, tuz, nane, tereyağı",
                            Name = "Yayla Çorbası",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Yoğurt, un ve yumurtayı karıştırın. Suyu ekleyip pişirin, tereyağında nane kavurup çorbaya ekleyin."
                        },
                        new
                        {
                            ID = 4,
                            CookingTime = "20 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Tarhana, su, domates salçası, biber salçası, tereyağı, tuz",
                            Name = "Tarhana Çorbası",
                            PreparationTime = "5 dakika",
                            RecipeExplanation = "Tarhanayı suda çözün. Salçaları tereyağında kavurun ve tarhanayı ekleyip pişirin."
                        },
                        new
                        {
                            ID = 5,
                            CookingTime = "25 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Domates, un, tereyağı, su, süt, tuz, karabiber",
                            Name = "Domates Çorbası",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Domatesleri rendeleyin. Un ve tereyağını kavurun, domatesleri ekleyin. Suyu ekleyip pişirin ve sütü ekleyin."
                        },
                        new
                        {
                            ID = 6,
                            CookingTime = "30 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Mantar, soğan, un, tereyağı, su, süt, tuz, karabiber",
                            Name = "Mantar Çorbası",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Soğanı kavurun, mantarları ekleyin. Un ekleyip kavurun, su ve sütü ekleyip pişirin."
                        },
                        new
                        {
                            ID = 7,
                            CookingTime = "40 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Tavuk göğsü, su, havuç, patates, kereviz, tuz, karabiber",
                            Name = "Tavuk Suyu Çorbası",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Tavuğu ve sebzeleri haşlayın, dIDikleyin ve suyu ile karıştırıp pişirin."
                        },
                        new
                        {
                            ID = 8,
                            CookingTime = "25 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Patates, havuç, kabak, kereviz, soğan, su, tuz, karabiber",
                            Name = "Sebze Çorbası",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Sebzeleri doğrayın, haşlayın ve blenderdan geçirip pişirin."
                        },
                        new
                        {
                            ID = 9,
                            CookingTime = "20 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Tavuk suyu, arpa şehriye, domates salçası, tereyağı, su, tuz, karabiber",
                            Name = "Şehriye Çorbası",
                            PreparationTime = "5 dakika",
                            RecipeExplanation = "Tereyağında salçayı kavurun. Tavuk suyu ve su ekleyip kaynatın, şehriyeleri ekleyip pişirin."
                        },
                        new
                        {
                            ID = 10,
                            CookingTime = "30 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Balkabağı, soğan, patates, krema, su, tuz, karabiber, zeytinyağı",
                            Name = "Kremalı Balkabağı Çorbası",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Soğanı kavurun, balkabağı ve patatesi ekleyin. Suyu ekleyip haşlayın, blenderdan geçirin ve krema ekleyin."
                        },
                        new
                        {
                            ID = 11,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Nohut, soğan, domates, biber, zeytinyağı, tuz, karabiber",
                            Name = "Nohut Yemeği",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Nohutları haşlayın, soğan ve biberi kavurun, domatesleri ekleyin. Haşlanmış nohutları ekleyin ve pişirin."
                        },
                        new
                        {
                            ID = 12,
                            CookingTime = "2 saat",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "10 kişilik",
                            Materials = "Buğday, nohut, kuru fasulye, kuru kayısı, kuru incir, kuru üzüm, ceviz, fındık, nar, su, şeker",
                            Name = "Aşure",
                            PreparationTime = "30 dakika",
                            RecipeExplanation = "Buğday, nohut ve kuru fasulyeyi ayrı ayrı haşlayın. Kuru kayısı, kuru incir ve kuru üzümü küçük doğrayın. Tüm malzemeleri büyük bir tencereye alın, su ekleyin ve kaynatın. Şekeri ekleyin ve karıştırarak pişirin. Aşure kıvamına gelince ocaktan alın ve kaselere dökün. Üzerini ceviz, fındık ve nar ile süsleyerek soğuk servis yapın."
                        },
                        new
                        {
                            ID = 13,
                            CookingTime = "30 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Bezelye, patates, havuç, soğan, zeytinyağı, tuz, karabiber",
                            Name = "Bezelye Yemeği",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Soğanı kavurun, patates ve havucu ekleyin. Bezelyeleri ve suyu ekleyip pişirin."
                        },
                        new
                        {
                            ID = 14,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Fasulye, soğan, domates, havuç, zeytinyağı, tuz, şeker",
                            Name = "Fasulye Pilaki",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Fasulyeleri haşlayın, soğan ve havucu kavurun. Domatesleri ekleyip fasulyeleri ekleyin ve pişirin."
                        },
                        new
                        {
                            ID = 15,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Kuru fasulye, soğan, domates, biber, zeytinyağı, tuz, karabiber",
                            Name = "Kuru Fasulye",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Kuru fasulyeleri haşlayın, soğan ve biberi kavurun. Domatesleri ekleyip fasulyeleri ekleyin ve pişirin."
                        },
                        new
                        {
                            ID = 16,
                            CookingTime = "30 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Pirinç, nohut, soğan, zeytinyağı, tuz, karabiber",
                            Name = "Nohutlu Pilav",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Nohutları haşlayın, soğanı kavurun. Pirinci ekleyin ve pişirin, nohutları ekleyin."
                        },
                        new
                        {
                            ID = 17,
                            CookingTime = "45 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Yeşil mercimek, soğan, domates, havuç, zeytinyağı, tuz, karabiber",
                            Name = "Yeşil Mercimek Yemeği",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Soğanı kavurun, havuç ve domatesi ekleyin. Mercimekleri ekleyip pişirin."
                        },
                        new
                        {
                            ID = 18,
                            CookingTime = "30 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Bezelye, patates, soğan, zeytinyağı, tuz, karabiber",
                            Name = "Patatesli Bezelye",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Soğanı kavurun, patates ve bezelyeyi ekleyin. Su ekleyip pişirin."
                        },
                        new
                        {
                            ID = 19,
                            CookingTime = "20 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Bulgur, domates, salatalık, yeşil soğan, nar ekşisi, zeytinyağı, tuz, karabiber",
                            Name = "Kısır",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Bulguru sıcak suyla ıslatın, domates, salatalık ve yeşil soğanı doğrayın. Karıştırın ve baharatları ekleyin."
                        },
                        new
                        {
                            ID = 20,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Kuru fasulye, pirinç, soğan, domates, biber, zeytinyağı, tuz",
                            Name = "Kuru Fasulye Pilav",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Kuru fasulyeleri haşlayın, pirinci hazırlayın. Fasulyeleri ve pilavı servis edin."
                        },
                        new
                        {
                            ID = 21,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Biber, pirinç, kıyma, soğan, domates, zeytinyağı, tuz, karabiber, nane",
                            Name = "Dolma",
                            PreparationTime = "20 dakika",
                            RecipeExplanation = "Kıymayı soğanla kavurun, pirinci ve baharatları ekleyin. Biberleri doldurup pişirin."
                        },
                        new
                        {
                            ID = 22,
                            CookingTime = "45 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Asma yaprağı, pirinç, kıyma, soğan, domates, zeytinyağı, tuz, karabiber, nane",
                            Name = "Zeytinyağlı Sarma",
                            PreparationTime = "30 dakika",
                            RecipeExplanation = "Pirinci, kıymayı ve baharatları karıştırın. Asma yapraklarına sarıp, zeytinyağı ile pişirin."
                        },
                        new
                        {
                            ID = 23,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Lahana, pirinç, kıyma, soğan, domates, zeytinyağı, tuz, karabiber, nane",
                            Name = "Lahana Sarma",
                            PreparationTime = "30 dakika",
                            RecipeExplanation = "Kıymayı soğanla kavurun, pirinci ve baharatları ekleyin. Lahana yapraklarına sarıp pişirin."
                        },
                        new
                        {
                            ID = 24,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Patlıcan, kıyma, pirinç, soğan, domates, zeytinyağı, tuz, karabiber, nane",
                            Name = "Patlıcan Dolması",
                            PreparationTime = "25 dakika",
                            RecipeExplanation = "Kıymayı soğanla kavurun, pirinci ve baharatları ekleyin. Patlıcanları doldurup pişirin."
                        },
                        new
                        {
                            ID = 25,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Kabak, kıyma, pirinç, soğan, domates, zeytinyağı, tuz, karabiber, nane",
                            Name = "Kabak Dolması",
                            PreparationTime = "20 dakika",
                            RecipeExplanation = "Kıymayı soğanla kavurun, pirinci ve baharatları ekleyin. Kabakları doldurup pişirin."
                        },
                        new
                        {
                            ID = 26,
                            CookingTime = "10 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Kısır, biber, domates, salatalık, nar ekşisi, zeytinyağı, tuz, karabiber",
                            Name = "Kısır Dolması",
                            PreparationTime = "20 dakika",
                            RecipeExplanation = "Kısırı hazırlayıp biberlerin içine doldurun. Domates ve salatalık ile servis edin."
                        },
                        new
                        {
                            ID = 27,
                            CookingTime = "45 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Dana eti, yoğurt, domates sosu, pilav, biber, tuz, karabiber",
                            Name = "İskender Dolması",
                            PreparationTime = "30 dakika",
                            RecipeExplanation = "Dana etini pişirin, biberleri doldurun ve yoğurt ile domates sosunu ekleyip pişirin."
                        },
                        new
                        {
                            ID = 28,
                            CookingTime = "10 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Kısır, marul yaprağı, domates, salatalık, nar ekşisi, zeytinyağı, tuz",
                            Name = "Kısır Sarma",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Kısırı marul yapraklarına sarın, domates ve salatalık ile servis edin."
                        },
                        new
                        {
                            ID = 29,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Patlıcan, biber, domates, kıyma, pirinç, soğan, zeytinyağı, tuz, karabiber",
                            Name = "Fırın Dolması",
                            PreparationTime = "30 dakika",
                            RecipeExplanation = "Patlıcan ve biberleri doldurun, domatesle kaplayıp fırında pişirin."
                        },
                        new
                        {
                            ID = 30,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Lahana yaprağı, pirinç, kıyma, soğan, domates, zeytinyağı, tuz, karabiber",
                            Name = "Zeytinyağlı Lahana Sarma",
                            PreparationTime = "30 dakika",
                            RecipeExplanation = "Pirinci ve kıymayı karıştırın, lahana yapraklarına sarın ve zeytinyağı ile pişirin."
                        },
                        new
                        {
                            ID = 31,
                            CookingTime = "2 saat",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Kuzu eti, soğan, sarımsak, zeytinyağı, tuz, karabiber, kekik",
                            Name = "Kuzu Tandır",
                            PreparationTime = "20 dakika",
                            RecipeExplanation = "Kuzu etini soğan ve sarımsakla birlikte zeytinyağında kavurun. Baharatları ekleyip fırında pişirin."
                        },
                        new
                        {
                            ID = 32,
                            CookingTime = "15 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "2 kişilik",
                            Materials = "Biftek, tuz, karabiber, tereyağı, sarımsak, kekik",
                            Name = "Biftek",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Bifteği tuz ve karabiberle tatlandırın. Tereyağında ve sarımsakla birlikte kızartın. Kekik serpin."
                        },
                        new
                        {
                            ID = 33,
                            CookingTime = "20 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Kıyma, soğan, ekmek içi, yumurta, tuz, karabiber, kimyon, pul biber",
                            Name = "Köfte",
                            PreparationTime = "20 dakika",
                            RecipeExplanation = "Kıymayı, soğanı ve baharatları yoğurun. Köfte şekli verip ızgarada pişirin."
                        },
                        new
                        {
                            ID = 34,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Dana eti, nohut, soğan, domates, biber, zeytinyağı, tuz, karabiber",
                            Name = "Etli Nohut Yemeği",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Etleri kavurun, soğan ve biberi ekleyin. Domates ve nohutları ilave edip pişirin."
                        },
                        new
                        {
                            ID = 35,
                            CookingTime = "40 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Dana eti, pirinç, soğan, tereyağı, tuz, karabiber, baharatlar",
                            Name = "Etli Pirinç Pilavı",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Etleri soğanla kavurun, pirinci ekleyin ve pişirin. Baharatları ekleyip servis yapın."
                        },
                        new
                        {
                            ID = 36,
                            CookingTime = "30 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "6 kişilik",
                            Materials = "Yufka, beyaz peynir, lor peyniri, maydanoz, zeytinyağı, tuz, karabiber",
                            Name = "Peynirli Börek",
                            PreparationTime = "20 dakika",
                            RecipeExplanation = "Yufkaları kat kat serin, peynir ve maydanoz karışımını aralarına koyun. Fırında pişirin."
                        },
                        new
                        {
                            ID = 37,
                            CookingTime = "20 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Yufka, beyaz peynir, maydanoz, zeytinyağı, tuz, karabiber",
                            Name = "Sigara Böreği",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Yufkayı dilimleyip peynirli karışımı koyun, sigara şeklinde sarıp kızartın."
                        },
                        new
                        {
                            ID = 38,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "8 kişilik",
                            Materials = "Un, su, maya, tuz, şeker",
                            Name = "Köy Ekmek",
                            PreparationTime = "20 dakika",
                            RecipeExplanation = "Un, su, maya, tuz ve şekeri yoğurun. Hamuru mayalandırıp fırında pişirin."
                        },
                        new
                        {
                            ID = 39,
                            CookingTime = "25 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Pizza hamuru, domates sosu, mozzarella peyniri, sucuk, zeytin, mantar, zeytinyağı",
                            Name = "Pizza",
                            PreparationTime = "20 dakika",
                            RecipeExplanation = "Hamuru açıp üzerine sos ve malzemeleri ekleyin. Fırında pişirin."
                        },
                        new
                        {
                            ID = 40,
                            CookingTime = "25 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "12 kişilik",
                            Materials = "Un, süt, yumurta, margarin, maya, tuz, beyaz peynir",
                            Name = "Poğaça",
                            PreparationTime = "20 dakika",
                            RecipeExplanation = "Hamuru yoğurun ve mayalandırın. Peynirli harcı koyup şekil verin, fırında pişirin."
                        },
                        new
                        {
                            ID = 41,
                            CookingTime = "15 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Domates, yeşil biber, yumurta, zeytinyağı, tuz, karabiber",
                            Name = "Menemen",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Biberleri ve domatesleri zeytinyağında kavurun, yumurtaları ekleyip karıştırarak pişirin."
                        },
                        new
                        {
                            ID = 42,
                            CookingTime = "10 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "2 kişilik",
                            Materials = "Yumurta, tereyağı, tuz, karabiber",
                            Name = "Sahanda Yumurta",
                            PreparationTime = "5 dakika",
                            RecipeExplanation = "Tereyağında yumurtaları kırıp pişirin. Tuz ve karabiberle tatlandırın."
                        },
                        new
                        {
                            ID = 43,
                            CookingTime = "0 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Çeşitli peynirler (beyaz peynir, kaşar, lor), zeytin, domates, salatalık, zeytinyağı",
                            Name = "Kahvaltılık Peynir Tabağı",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Peynirleri dilimleyip tabağa yerleştirin. Zeytin, domates ve salatalık ekleyin."
                        },
                        new
                        {
                            ID = 44,
                            CookingTime = "10 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "6 kişilik",
                            Materials = "Güllaç yaprağı, süt, şeker, gül suyu, ceviz, nar",
                            Name = "Güllaç",
                            PreparationTime = "20 dakika",
                            RecipeExplanation = "Sütü ve şekeri ısıtın. Güllaç yapraklarını sütle ıslatarak üst üste dizin. Aralarına ceviz serpin. Gül suyu ekleyin. Üzerine nar taneleri ile süsleyin ve soğuk servis yapın."
                        },
                        new
                        {
                            ID = 45,
                            CookingTime = "10 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "2 kişilik",
                            Materials = "Sosis, yumurta, tereyağı, tuz, karabiber",
                            Name = "Yumurtalı Sosis",
                            PreparationTime = "5 dakika",
                            RecipeExplanation = "Sosisleri tereyağında kızartın. Üzerine yumurtayı kırıp pişirin, tuz ve karabiberle tatlandırın."
                        },
                        new
                        {
                            ID = 46,
                            CookingTime = "20 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Spaghetti, yumurta, parmesan peyniri, pastırma, sarımsak, zeytinyağı, tuz, karabiber",
                            Name = "Spaghetti Carbonara",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Spaghettiyi haşlayın. Pastırmayı ve sarımsağı zeytinyağında kavurun, yumurta ve peynir karışımını ekleyin. Spaghettiyi karışıma ekleyip karıştırın."
                        },
                        new
                        {
                            ID = 47,
                            CookingTime = "15 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Fettucine, tereyağı, krema, parmesan peyniri, sarımsak, tuz, karabiber",
                            Name = "Fettucine Alfredo",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Fettucineyi haşlayın. Tereyağını eritip kremayı ekleyin, peynirle karıştırın. Sosu makarnaya döküp karıştırın."
                        },
                        new
                        {
                            ID = 48,
                            CookingTime = "20 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Penne, domates sosu, kırmızı biber, sarımsak, zeytinyağı, tuz, karabiber, maydanoz",
                            Name = "Penne Arrabbiata",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Penneyi haşlayın. Sarımsağı ve kırmızı biberi zeytinyağında kavurun, domates sosunu ekleyin. Sosu makarnaya döküp maydanoz ile süsleyin."
                        },
                        new
                        {
                            ID = 49,
                            CookingTime = "30 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Makarna, cheddar peyniri, süt, tereyağı, un, tuz, karabiber, muskat cevizi",
                            Name = "Mac and Cheese",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Makarna haşlanır. Sos için tereyağı ve unu kavurun, süt ekleyip koyulaşana kadar pişirin. Peynirleri ekleyip eritin. Sosu makarnaya dökün, fırında 15 dakika pişirin."
                        },
                        new
                        {
                            ID = 50,
                            CookingTime = "45 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Makarna, kıyma, domates sosu, soğan, sarımsak, havuç, kereviz, zeytinyağı, tuz, karabiber, kekik",
                            Name = "Bolognese Soslu Makarna",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Kıymayı soğan, sarımsak, havuç ve kereviz ile kavurun. Domates sosunu ekleyip kısık ateşte pişirin. Makarnayı haşlayıp sosla karıştırın."
                        },
                        new
                        {
                            ID = 51,
                            CookingTime = "40 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Enginar, zeytinyağı, limon, soğan, havuç, bezelye, tuz, karabiber, dereotu",
                            Name = "Zeytinyağlı Enginar",
                            PreparationTime = "20 dakika",
                            RecipeExplanation = "Enginarları limonlu suya bekletin. Soğanı ve havucu zeytinyağında kavurun. Enginarları ekleyip bezelye ve su ilave edin. Piştikten sonra dereotu ile süsleyin."
                        },
                        new
                        {
                            ID = 52,
                            CookingTime = "20 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "6 kişilik",
                            Materials = "Kadayıf, tuzsuz peynir, tereyağı, şeker, su, limon",
                            Name = "Künefe",
                            PreparationTime = "30 dakika",
                            RecipeExplanation = "Kadayıfı tereyağı ile karıştırın ve yarısını tepsiye yayın. Üzerine peyniri koyun ve kalan kadayıfı üzerine kapatın. Orta ateşte altın rengi alana kadar pişirin. Şerbet için şeker, su ve limonu kaynatın ve sıcak künefenin üzerine dökün."
                        },
                        new
                        {
                            ID = 53,
                            CookingTime = "30 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Patates, soğan, domates, biber, zeytinyağı, tuz, karabiber, pul biber",
                            Name = "Patates Yemeği",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Patatesleri ve soğanları doğrayıp zeytinyağında kavurun. Domates ve biberleri ekleyin, baharatlarla tatlandırın. Kısık ateşte pişirin."
                        },
                        new
                        {
                            ID = 54,
                            CookingTime = "25 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Kabak, zeytinyağı, sarımsak, tuz, karabiber, kekik, parmesan peyniri",
                            Name = "Fırında Kabak",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Kabları dilimleyip zeytinyağı, sarımsak ve baharatlarla harmanlayın. Fırın tepsisine dizip parmesan peyniri serpin, fırında pişirin."
                        },
                        new
                        {
                            ID = 55,
                            CookingTime = "20 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Karnabahar, un, yumurta, tuz, karabiber, sıvı yağ",
                            Name = "Karnabahar Kızartması",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Karnabaharları çiçeklerine ayırın. Un ve yumurtaya bulayıp sıvı yağda kızartın. Tuz ve karabiber ile tatlandırın."
                        },
                        new
                        {
                            ID = 56,
                            CookingTime = "45 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Pirinç, süt, şeker, vanilin, su, tarçın",
                            Name = "Sütlaç",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Pirinçleri suyla haşlayın. Sütü ve şekeri ekleyip karıştırarak pişirin. Vanilini ekleyip karıştırın. Kaselere döküp soğutun, tarçın serpin."
                        },
                        new
                        {
                            ID = 57,
                            CookingTime = "45 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "8 kişilik",
                            Materials = "Yufka, ceviz, tereyağı, şeker, su, limon suyu",
                            Name = "Baklava",
                            PreparationTime = "30 dakika",
                            RecipeExplanation = "Yufkaları tereyağı ile yağlayarak üst üste koyun. Cevizi serpin ve dilimleyin. Fırında pişirip şerbet dökün."
                        },
                        new
                        {
                            ID = 58,
                            CookingTime = "60+ dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Patates, tereyağı, kaşar peyniri, zeytin, mısır, sosis, mayonez, ketçap, tuz",
                            Name = "Kumpir",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Patatesleri fırında pişirin. Kumpirleri kesip içlerini tereyağı ve kaşar ile karıştırın. Üzerine zeytin, mısır, sosis ve sosları ekleyin."
                        },
                        new
                        {
                            ID = 59,
                            CookingTime = "30 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "8 kişilik",
                            Materials = "Yumurta, şeker, un, irmik, yoğurt, kabartma tozu, limon suyu, şeker",
                            Name = "Revani",
                            PreparationTime = "15 dakika",
                            RecipeExplanation = "Yumurta ve şekeri çırpın, diğer malzemeleri ekleyip karıştırın. Fırında pişirin ve soğuduktan sonra şerbet dökün."
                        },
                        new
                        {
                            ID = 60,
                            CookingTime = "20 dakika",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HowManyPerson = "4 kişilik",
                            Materials = "Süt, şeker, kakao, nişasta, vanilin",
                            Name = "Puding",
                            PreparationTime = "10 dakika",
                            RecipeExplanation = "Süt, şeker ve kakao karışımını kaynatın. Nişasta ve vanilini ekleyip karıştırarak pişirin. Kaselere döküp soğutun."
                        });
                });

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.Info", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 21, 20, 42, 45, 316, DateTimeKind.Utc).AddTicks(8637));

                    b.Property<string>("inf")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("ID");

                    b.ToTable("Infos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inf = "Yemeklerin lezzeti büyük ölçüde kullanılan malzemelerin kalitesine bağlıdır. Taze ve kaliteli malzemeler kullanmaya özen gösterin."
                        },
                        new
                        {
                            ID = 2,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inf = "Tarife sadık kalmak, doğru miktarda malzeme kullanmak önemlidir. Özellikle tuz, baharat ve şeker gibi tatları dikkatlice ölçün."
                        },
                        new
                        {
                            ID = 3,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inf = "Yemek yapmaya başlamadan önce tüm malzemeleri hazırlayın. Bu, yemek yapma sürecini daha düzenli ve hızlı hale getirir."
                        },
                        new
                        {
                            ID = 4,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inf = "Pişirme sırasında ısıyı doğru ayarlamak önemlidir. Kısık ateşte pişirilen yemekler genellikle daha lezzetli ve dengeli olur."
                        },
                        new
                        {
                            ID = 5,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inf = "Baharatları yemeklerin pişirme sürecinin başında değil, genellikle sonlarına doğru eklemek, baharatların aromasını kaybetmesini engeller."
                        },
                        new
                        {
                            ID = 6,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inf = "Pişirdiğiniz yemekleri servisten önce bir süre dinlendirmek, lezzetlerin birbirine karışmasına ve yemeklerin daha iyi bir tat profilinin oluşmasına yardımcı olur."
                        },
                        new
                        {
                            ID = 7,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inf = "Yemekleri gereğinden fazla pişirmek lezzetlerini kaybettirebilir. Tarife göre önerilen süreleri dikkate alın ve pişirme süresini kontrol edin."
                        },
                        new
                        {
                            ID = 8,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inf = "Yemeklerde tuz ve şeker miktarını dengelemek önemlidir. Tatları dengede tutmak için küçük miktarlarda ekleyin ve tadına bakarak ayarlayın."
                        },
                        new
                        {
                            ID = 9,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inf = "Sosları yemeklerin üzerine dökmeden önce, sosun kıvamını ve tadını kontrol edin. Sosları yemekle aynı anda pişirmek, daha iyi bir uyum sağlar."
                        },
                        new
                        {
                            ID = 10,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inf = "Yemeklerin sunumu da en az lezzeti kadar önemlidir. Güzel bir sunum, yemeklerin tadını daha da artırabilir ve iştah açıcı hale getirebilir."
                        });
                });

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.MyUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhotoId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Myusers");
                });

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.Photos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 21, 20, 42, 45, 317, DateTimeKind.Utc).AddTicks(915));

                    b.Property<int?>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FoodId");

                    b.HasIndex("ID");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 1,
                            PhotoPath = "~/img/1.1.jpg"
                        },
                        new
                        {
                            ID = 2,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 1,
                            PhotoPath = "~/img/1.2.jpg"
                        },
                        new
                        {
                            ID = 3,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 2,
                            PhotoPath = "~/img/2.1.jpg"
                        },
                        new
                        {
                            ID = 4,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 2,
                            PhotoPath = "~/img/2.2.jpg"
                        },
                        new
                        {
                            ID = 5,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 3,
                            PhotoPath = "~/img/3.1.jpg"
                        },
                        new
                        {
                            ID = 6,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 3,
                            PhotoPath = "~/img/3.2.jpg"
                        },
                        new
                        {
                            ID = 7,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 4,
                            PhotoPath = "~/img/4.1.jpg"
                        },
                        new
                        {
                            ID = 8,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 4,
                            PhotoPath = "~/img/4.2.jpg"
                        },
                        new
                        {
                            ID = 9,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 5,
                            PhotoPath = "~/img/5.1.jpg"
                        },
                        new
                        {
                            ID = 10,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 5,
                            PhotoPath = "~/img/5.2.jpg"
                        },
                        new
                        {
                            ID = 11,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 6,
                            PhotoPath = "~/img/6.1.jpg"
                        },
                        new
                        {
                            ID = 12,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 6,
                            PhotoPath = "~/img/6.2.jpg"
                        },
                        new
                        {
                            ID = 13,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 7,
                            PhotoPath = "~/img/7.1.jpg"
                        },
                        new
                        {
                            ID = 14,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 7,
                            PhotoPath = "~/img/7.2.jpg"
                        },
                        new
                        {
                            ID = 15,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 8,
                            PhotoPath = "~/img/8.1.jpg"
                        },
                        new
                        {
                            ID = 16,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 8,
                            PhotoPath = "~/img/8.2.jpg"
                        },
                        new
                        {
                            ID = 17,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 9,
                            PhotoPath = "~/img/9.1.jpg"
                        },
                        new
                        {
                            ID = 18,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 9,
                            PhotoPath = "~/img/9.2.jpg"
                        },
                        new
                        {
                            ID = 19,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 10,
                            PhotoPath = "~/img/10.1.jpg"
                        },
                        new
                        {
                            ID = 21,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 11,
                            PhotoPath = "~/img/11.1.jpg"
                        },
                        new
                        {
                            ID = 88,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 12,
                            PhotoPath = "~/img/12.1.jpg"
                        },
                        new
                        {
                            ID = 22,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 13,
                            PhotoPath = "~/img/13.1.jpg"
                        },
                        new
                        {
                            ID = 23,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 14,
                            PhotoPath = "~/img/14.1.jpg"
                        },
                        new
                        {
                            ID = 24,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 15,
                            PhotoPath = "~/img/15.1.jpg"
                        },
                        new
                        {
                            ID = 25,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 15,
                            PhotoPath = "~/img/15.2.jpg"
                        },
                        new
                        {
                            ID = 26,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 16,
                            PhotoPath = "~/img/16.1.jpg"
                        },
                        new
                        {
                            ID = 27,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 16,
                            PhotoPath = "~/img/16.2.jpg"
                        },
                        new
                        {
                            ID = 28,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 17,
                            PhotoPath = "~/img/17.1.jpg"
                        },
                        new
                        {
                            ID = 29,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 18,
                            PhotoPath = "~/img/18.1.jpg"
                        },
                        new
                        {
                            ID = 30,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 19,
                            PhotoPath = "~/img/19.1.jpg"
                        },
                        new
                        {
                            ID = 31,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 20,
                            PhotoPath = "~/img/20.1.jpg"
                        },
                        new
                        {
                            ID = 32,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 21,
                            PhotoPath = "~/img/21.1.jpg"
                        },
                        new
                        {
                            ID = 33,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 22,
                            PhotoPath = "~/img/22.1.jpg"
                        },
                        new
                        {
                            ID = 34,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 23,
                            PhotoPath = "~/img/23.1.jpg"
                        },
                        new
                        {
                            ID = 35,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 23,
                            PhotoPath = "~/img/23.2.jpg"
                        },
                        new
                        {
                            ID = 36,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 24,
                            PhotoPath = "~/img/24.1.jpg"
                        },
                        new
                        {
                            ID = 37,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 24,
                            PhotoPath = "~/img/24.2.jpg"
                        },
                        new
                        {
                            ID = 38,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 25,
                            PhotoPath = "~/img/25.1.jpg"
                        },
                        new
                        {
                            ID = 39,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 25,
                            PhotoPath = "~/img/25.2.jpg"
                        },
                        new
                        {
                            ID = 40,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 26,
                            PhotoPath = "~/img/26.1.jpg"
                        },
                        new
                        {
                            ID = 41,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 27,
                            PhotoPath = "~/img/27.1.jpg"
                        },
                        new
                        {
                            ID = 42,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 28,
                            PhotoPath = "~/img/28.1.jpg"
                        },
                        new
                        {
                            ID = 43,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 29,
                            PhotoPath = "~/img/29.1.jpg"
                        },
                        new
                        {
                            ID = 44,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 30,
                            PhotoPath = "~/img/30.1.jpg"
                        },
                        new
                        {
                            ID = 45,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 31,
                            PhotoPath = "~/img/31.1.jpg"
                        },
                        new
                        {
                            ID = 46,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 31,
                            PhotoPath = "~/img/31.2.jpg"
                        },
                        new
                        {
                            ID = 47,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 32,
                            PhotoPath = "~/img/32.1.jpg"
                        },
                        new
                        {
                            ID = 48,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 33,
                            PhotoPath = "~/img/33.1.jpg"
                        },
                        new
                        {
                            ID = 49,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 33,
                            PhotoPath = "~/img/33.2.jpg"
                        },
                        new
                        {
                            ID = 50,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 34,
                            PhotoPath = "~/img/34.1.jpg"
                        },
                        new
                        {
                            ID = 51,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 34,
                            PhotoPath = "~/img/34.2.jpg"
                        },
                        new
                        {
                            ID = 52,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 35,
                            PhotoPath = "~/img/35.1.jpg"
                        },
                        new
                        {
                            ID = 53,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 36,
                            PhotoPath = "~/img/36.1.jpg"
                        },
                        new
                        {
                            ID = 54,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 36,
                            PhotoPath = "~/img/36.2.jpg"
                        },
                        new
                        {
                            ID = 55,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 37,
                            PhotoPath = "~/img/37.1.jpg"
                        },
                        new
                        {
                            ID = 56,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 37,
                            PhotoPath = "~/img/37.2.jpg"
                        },
                        new
                        {
                            ID = 57,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 38,
                            PhotoPath = "~/img/38.1.jpg"
                        },
                        new
                        {
                            ID = 58,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 39,
                            PhotoPath = "~/img/39.1.jpg"
                        },
                        new
                        {
                            ID = 59,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 40,
                            PhotoPath = "~/img/40.1.jpg"
                        },
                        new
                        {
                            ID = 60,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 41,
                            PhotoPath = "~/img/41.1.jpg"
                        },
                        new
                        {
                            ID = 61,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 42,
                            PhotoPath = "~/img/42.1.jpg"
                        },
                        new
                        {
                            ID = 62,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 42,
                            PhotoPath = "~/img/42.2.jpg"
                        },
                        new
                        {
                            ID = 63,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 43,
                            PhotoPath = "~/img/43.1.jpg"
                        },
                        new
                        {
                            ID = 64,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 44,
                            PhotoPath = "~/img/44.1.jpg"
                        },
                        new
                        {
                            ID = 65,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 45,
                            PhotoPath = "~/img/45.1.jpg"
                        },
                        new
                        {
                            ID = 66,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 46,
                            PhotoPath = "~/img/46.1.jpg"
                        },
                        new
                        {
                            ID = 67,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 47,
                            PhotoPath = "~/img/47.1.jpg"
                        },
                        new
                        {
                            ID = 68,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 47,
                            PhotoPath = "~/img/47.2.jpg"
                        },
                        new
                        {
                            ID = 69,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 48,
                            PhotoPath = "~/img/48.1.jpg"
                        },
                        new
                        {
                            ID = 70,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 48,
                            PhotoPath = "~/img/48.2.jpg"
                        },
                        new
                        {
                            ID = 71,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 49,
                            PhotoPath = "~/img/49.1.jpg"
                        },
                        new
                        {
                            ID = 72,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 49,
                            PhotoPath = "~/img/49.2.jpg"
                        },
                        new
                        {
                            ID = 73,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 50,
                            PhotoPath = "~/img/50.1.jpg"
                        },
                        new
                        {
                            ID = 74,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 50,
                            PhotoPath = "~/img/50.2.jpg"
                        },
                        new
                        {
                            ID = 75,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 51,
                            PhotoPath = "~/img/51.1.jpg"
                        },
                        new
                        {
                            ID = 76,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 52,
                            PhotoPath = "~/img/52.1.jpg"
                        },
                        new
                        {
                            ID = 77,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 53,
                            PhotoPath = "~/img/53.1.jpg"
                        },
                        new
                        {
                            ID = 78,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 54,
                            PhotoPath = "~/img/54.1.jpg"
                        },
                        new
                        {
                            ID = 79,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 55,
                            PhotoPath = "~/img/55.1.jpg"
                        },
                        new
                        {
                            ID = 80,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 56,
                            PhotoPath = "~/img/56.1.jpg"
                        },
                        new
                        {
                            ID = 81,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 56,
                            PhotoPath = "~/img/56.2.jpg"
                        },
                        new
                        {
                            ID = 82,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 57,
                            PhotoPath = "~/img/57.1.jpg"
                        },
                        new
                        {
                            ID = 83,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 57,
                            PhotoPath = "~/img/57.2.jpg"
                        },
                        new
                        {
                            ID = 84,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 58,
                            PhotoPath = "~/img/58.1.jpg"
                        },
                        new
                        {
                            ID = 86,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 59,
                            PhotoPath = "~/img/58.1.jpg"
                        },
                        new
                        {
                            ID = 87,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 60,
                            PhotoPath = "~/img/60.1.jpg"
                        });
                });

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.CategoryFood", b =>
                {
                    b.HasOne("Recipe.Entities.Model.Concrete.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recipe.Entities.Model.Concrete.Food", "Food")
                        .WithMany("Categorys")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.Comments", b =>
                {
                    b.HasOne("Recipe.Entities.Model.Concrete.Food", "Food")
                        .WithMany("Comments")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.Photos", b =>
                {
                    b.HasOne("Recipe.Entities.Model.Concrete.Food", "Food")
                        .WithMany("OtherPictures")
                        .HasForeignKey("FoodId");

                    b.HasOne("Recipe.Entities.Model.Concrete.MyUser", "User")
                        .WithOne("UserPhoto")
                        .HasForeignKey("Recipe.Entities.Model.Concrete.Photos", "UserId");

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.Food", b =>
                {
                    b.Navigation("Categorys");

                    b.Navigation("Comments");

                    b.Navigation("OtherPictures");
                });

            modelBuilder.Entity("Recipe.Entities.Model.Concrete.MyUser", b =>
                {
                    b.Navigation("UserPhoto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
